SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `SportsActivities` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `SportsActivities`;

CREATE TABLE `ActivityType` (
  `activityType` varchar(20) NOT NULL,
  `startDate` date NOT NULL,
  `endDate` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `ActivityType` (`activityType`, `startDate`, `endDate`) VALUES
('Cricket', '2020-03-05', '2021-07-20'),
('Football', '2021-02-01', '2021-06-25'),
('Golf', '2021-03-01', '2021-06-20'),
('Tennis', '2021-03-15', '2021-07-15');


ALTER TABLE `ActivityType`
  ADD PRIMARY KEY (`activityType`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
